# Generated by Django 4.1.2 on 2022-10-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('codCidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAdministrador',
            fields=[
                ('idemail', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmailUsuario',
            fields=[
                ('idemail', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('codEstado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('codSituacao', models.AutoField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=8)),
                ('id_usu_email', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.emailusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('codResgate', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('id_cid_denuncia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.cidade')),
                ('id_est_denuncia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.estado')),
                ('id_sit_denuncia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.situacao')),
                ('id_usu_denuncia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('codDenuncia', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('id_cid_denuncia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.cidade')),
                ('id_sit_denuncia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.situacao')),
                ('id_usu_denuncia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=8)),
                ('id_ema_adm', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.emailadministrador')),
            ],
        ),
    ]
