# Generated by Django 4.1.2 on 2022-11-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_alter_denuncia_id_usu_denuncia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resgate',
            name='id_usu_resgate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.usuario'),
        ),
    ]
