# Generated by Django 4.1.2 on 2022-11-02 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animais', '0005_rename_id_cid_denuncia_denuncia_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resgate',
            name='usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
